const PostsData = [
{
    id:1,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
{
    id:2,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
{
    id:3,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
{
    id:4,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
{
    id:5,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
{
    id:6,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
{
    id:7,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
{
    id:8,
    username:"praispranav",
    image:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    like:23,
    liked:false,
    comments:{
        id:1,
        username:"Pranav",
        comment:"This is First Comment",
    },
    profileimage:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    about:"This is along about is along about is along about vis along about is along about is along about is along about ",
    saved:false,
},
]

export default PostsData;